
services:
  app:
    build: .
    container_name: scale-app
    volumes:
      - ./logs:/app/logs
    networks:
      - scale-network

  nginx:
    image: nginx:stable
    container_name: scale-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - scale-network

networks:
  scale-network:
    driver: bridge