services:
 
  app:
    build: .
    container_name: scale-app
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./items.json:/app/items.json
    networks:
      - scale-network
    environment:
      - JSON_FILE_PATH=/app/items.json


  nginx:
    image: nginx:stable
    container_name: scale-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - scale-network

networks:
  scale-network:
    driver: bridge