version: '3.8'
services:
  scale-service:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    container_name: scale-service
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    restart: always
    

networks:
  scale-network:
    driver: bridge