version: '3.8'
services:
  scale-service:
    build: .
    container_name: scale-service
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    restart: always
    environment:
      - JAVA_OPTS=-Xmx1g -Xms1g
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/scale/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G 