server:
  port: 8080
  servlet:
    context-path: /scale

# Optional: Add these if you want to customize the logging colors
spring:
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
  profiles:
    active: prod