server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /scale/api

# Optional: Add these if you want to customize the logging colors
spring:
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
      add-mappings: false
