server:
  port: 8080
  servlet:
    context-path: /scale

spring:
  output:
    ansi:
      enabled: never
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

logging:
  level:
    'com.example.scale': INFO
    'org.springframework': WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/api.log 